### ISSUE TITLE
Support Node 6

### ISSUE THREAD

**Issue by TheDancingCode** [ChristianMurphy/postcss-combine-duplicated-selectors#100]
Currently, the package supports only the latest major version of Node, due to this directive in `package.json`:
```
"engines": {
    "node": ">=8"
}
```
However, there's nothing in your code that prevents compatibility with version 6 of Node, which also happens to be the recommended version for most users.

Trying to install the module with yarn results in the following error:
```
error postcss-combine-duplicated-selectors@3.0.0: The engine "node" is incompatible with this module. Expected version ">=8".
```
Installation fails, while the module would in fact work correctly. Setting the required engine to node versions 6 and up instead of 8 and up would make it usable for more users.

**Comment by ChristianMurphy** [comment]
Hey @TheDancingCode! :wave: 
Thanks for opening an issue!
Node 6 drops into maintaince [April 2018](https://github.com/nodejs/Release#release-schedule1).
My original plan was to drop support now to avoid another major version bump to drop support then.
If it would be beneficial to keep Node 6 support until then, I'd be happy to re-add it. :slightly_smiling_face:
