### ISSUE TITLE
Postcss is not defined.

### ISSUE THREAD

**Issue by ItsEddie** [ChristianMurphy/postcss-combine-duplicated-selectors#143]
Hey there,

Recieving this error both [here]( https://npm.runkit.com/postcss-combine-duplicated-selectors) and on the CLI. Installed this package globally with the following command:

`npm install -g postcss-combine-duplicated-selectors`

Any ideas?

**Edit**:

After a closer look I realized that you probably need Postcss-cli for this (new to Node.js.) Now I recieve the following error:

`× Plugin Error: Cannot find module '*.css'` 
`× Plugin Error: Cannot find module 'style0.css'`

with the given command:

`postcss --use postcss-combine-duplicated-selectors *.css`

**Double Edit**: Switched the file name and the --use command around and it seems to work now. 

**Triple Edit**: Working solution: Install postcss-cli (which is probably common knowledge in the community, not sure.) Then swap around the use statement with the file name.

`postcss style.css --use postcss-combine-duplicated-selectors -o style1.css)`

**Comment by ChristianMurphy** [comment]
Thanks @ItsEddie! :bow:
`postcss-cli` has updated their options since the docs for `postcss-combine-duplicated-selectors` were written.
If you'd be interested, pull request updating the README would be welcome. :+1: 
If not, I'll set aside some time soon to update the docs with the new options.

**Comment by ItsEddie** [comment]
Absolutely, if you ever want documentation for anything feel free to ask me I'd be glad to help you out. I've just requested a small change to the readme to fix this problem.  Going to enjoy my beer! Have a great evening.

**Comment by ChristianMurphy** [comment]
Thanks @ItsEddie! :beers: 
The updated README publish to NPM in version 4.0.2.
