### ISSUE TITLE
Unfortunately, mq-packer is dead :(

### ISSUE THREAD

**Issue by qodesmith** [ChristianMurphy/postcss-combine-duplicated-selectors#327]
I've been happily using this plugin + [mq-packer](https://github.com/hail2u/node-css-mqpacker) together for a while now. Unfortunately, [mq-packer](https://github.com/hail2u/node-css-mqpacker) has (recently?) been deprecated and is no longer under development. Any other suggestions?

**Comment by ChristianMurphy** [comment]
There is a fork in the works that should continue to offer the functionality and updates.
https://github.com/simbo/css-mqpacker-sort-mediaqueries/issues/1#issuecomment-482150079

**Comment by ChristianMurphy** [comment]
https://github.com/SassNinja/postcss-combine-media-query looks like a good alternative
