### ISSUE TITLE
CSS source map gets inline inside file

### ISSUE THREAD

**Issue by ashfahan** [ChristianMurphy/postcss-combine-duplicated-selectors#360]
After using postcss-combine-duplicated-selectors the css source map gets inline inside file.
its not the behavior we expected.

the code changes can be seen clearly in this [commit](https://github.com/fluid-framework/Fluid/commit/b10abf7a10aaeee14132b5835798ee47dd94e4c3#diff-57f772c41016f518b8679de0d89856f2) 

although the plugin works like a charm 🌟

**Comment by ChristianMurphy** [comment]
@ashfahan interesting :thinking: 
Were you trying out any other plugins at the time?
And/or was other configuration changed?

`postcss-combine-duplicated-selectors` shouldn't modify source maps.

**Comment by ashfahan** [comment]
@ChristianMurphy i tried remove other plugins and tried giving it a vanilla but still it modified the source maps

**Comment by ChristianMurphy** [comment]
@ashfahan looks like its a Postcss CLI option. https://github.com/postcss/postcss-cli
Try adding `--map` or `--no-map`.

**Comment by ashfahan** [comment]
Thanks @ChristianMurphy `--map` did solved it `--no-map` removes sourceMappingURL from the file

**Comment by ashfahan** [comment]
Thanks for quick response. I ran few tests and yes it 👌.

**Comment by ChristianMurphy** [comment]
Happy to help
