### ISSUE TITLE
Does it support css variables?

### ISSUE THREAD

**Issue by tanekim77** [ChristianMurphy/postcss-combine-duplicated-selectors#559]
Does it support a case like this, with :root? I am getting an error when I do that.
:root {
    --a: red;
}
.b{
   color: var(--a);
}
.b{
   color: var(--a);
}

**Comment by ChristianMurphy** [comment]
it does.
here is the test case that shows variables working.
https://github.com/ChristianMurphy/postcss-combine-duplicated-selectors/blob/38bd6f1fca70ba18db9ffe5fcd9b78142a5e8cbe/test/duplicated-properties.js#L115-L133
