### ISSUE TITLE
Installation command has typo

### ISSUE THREAD

**Issue by deadmantfa** [ChristianMurphy/postcss-combine-duplicated-selectors#588]
npm install --save-dev postcsss postcss-combine-duplicated-selectors
 or
yarn add --dev postcsss postcss-combine-duplicated-selectors

needs to be

npm install --save-dev **postcss** postcss-combine-duplicated-selectors
 or
yarn add --dev **postcss** postcss-combine-duplicated-selectors

**Comment by ChristianMurphy** [comment]
A PR to update the doc with the correction would be welcome!
