### ISSUE TITLE
Identical media rules lose selectors

### ISSUE THREAD

**Issue by ChristianMurphy** [ChristianMurphy/postcss-combine-duplicated-selectors#63]
Minimal reproduction code

Input CSS

``` css
@media print { .one{} }
@media print { .one{} }
```

Expected Output

``` css
@media print { .one{} }
@media print { .one{} }
```

Actual Output

``` css
@media print { .one{} }
@media print { }
```

**Comment by ChristianMurphy** [comment]
related to #58

**Comment by ChristianMurphy** [comment]
@kristoferjoseph This is a blocker for release 2.2.0.
I'm looking into the root cause now.
Insights into what may be happening would be appreciated.

**Comment by ChristianMurphy** [comment]
hmm it looks like partial deduplication is happening
e.g.

``` css
@media print { .one{} }
@media print { .one{} .two {} }
```

becomes

``` css
@media print { .one {} }
@media print { .two {} }
```

**Comment by ChristianMurphy** [comment]
The easiest way to update this would be to move to a stack based system.
Start with a root map, whenever an at rule is entered push a new map work on that, on exit at rule pop top element of stack.

**Comment by ChristianMurphy** [comment]
postcss 5 doesn't have built in visitor pattern helpers.
postcss 6 will include helpers by default.
In the mean time a visitor helper will need to be added.

Example visitor: https://github.com/pascalduez/postcss-apply/blob/master/src/visitor.js
Example of desired API: https://github.com/thejameskyle/babel-handbook/blob/master/translations/en/plugin-handbook.md#toc-visitors

**Comment by kristoferjoseph** [comment]
Hmm seems to be working as expected to me. The end effect is that a duplicate selector is removed.

**Comment by ChristianMurphy** [comment]
> Hmm seems to be working as expected to me. The end effect is that a duplicate selector is removed.

@kristoferjoseph Maybe I'm misunderstanding what the intended functionality of the patch.
I interpreted:

> I don't feel that this plugin should combine media queries though. I feel that this should be handled by something like mq-packer.

To mean that selectors should be deduplicated within media rules, but that selectors should not be deduped across media rules.
I'm also thinking ahead toward to adding less and sass nested selector support for this feature.

E.G.

``` css
@media print {
  .one {}
  .one {}
}
```

should become

``` css
@media print {
  .one {}
}
```

---

``` css
@media print { .one {} }
@media print { .one {} }
```

should remain

``` css
@media print { .one {} }
@media print { .one {} }
```

---

``` less
.one {
  @media print {
    .two {}
  }
}
.one {
  @media print {
    .two {}
  }
}
```

should become

``` less
.one {
  @media print {
    .two {}
  }
 @media print {
    .two {}
  }
}

// or

@media print {
  .one .two {}
}

@media print {
  .one .two {}
}
```

**Comment by ChristianMurphy** [comment]
Is the actual expected behavior the below?

``` css
@media print {
  .one {
    color: blue;
  }
}
@media print {
  .one {
    background-color: red;
  }
}
```

would become

``` css
@media print {
  .one {
    color: blue;
    background-color: red;
  }
}
```

**Comment by kristoferjoseph** [comment]
This patch was to remove duplicate selectors while respecting the selector's scope. 

Meaning it used to only work in the root scope and disrespected media query scope. Now it removes duplicates in the correct scope. 

@media { .one {} .one{} } is the same as @media { .one {} } @media { .one {} } in this respect. 

The end result in CSS is correctly removing a duplicate while respecting the scope it was authored in.

**Comment by ChristianMurphy** [comment]
What I am saying is the plugin should be consistent.

given two media rules

``` css
@media print { .one {} .one {} }
@media print { .one {} .one {} }
```

A user could expect all duplicated at rules and duplicated selectors to be combined.

``` css
@media print { .one {} }
```

Or a user could expect for all selectors to be combined within a scope.

``` css
@media print { .one {} }
@media print { .one {} }
```

Currently the code combines duplicated selectors across matching scopes, but leaves the other scope and any dangling selectors behind.
To me this seems like unexpected behavior.

``` css
@media print { .one {} }
@media print { }
```

**Comment by kristoferjoseph** [comment]
I hear you.
Given this input:
```
@media print { .one {} .one {} }
@media print { .one {} .one {} }
```
if you are removing duplicate selectors then the following output is a bug. Since that is a duplicate selector in the same scope.
```
@media print { .one {} }
@media print { .one {} }
```
This output actually does what the user wants
```
@media print { .one {} }
@media print { }
```
What it doesn't do is delete an empty atrule.

**Comment by ChristianMurphy** [comment]
> which this is your plugin so your decision, but I still feel like it would be better to let mq-packer deal with media queries and have combine duplicate selectors combine selectors.

And I agree, I'm trying to find the best experience for people using mq-packer and those not.

What I'll do for now is cut, 2.2.0. Your change is a definite improvement for handling `@media` compared to before. 👍 

And I'll leave this open as something to be resolved in 2.3.0

**Comment by ChristianMurphy** [comment]
actually, I changed my mind, I updated the message in the readme a bit and will leave code as is.

**Comment by ChristianMurphy** [comment]
@kristoferjoseph release 2.2.0 has been cut with the media query fix, thanks for your contributions!
