### ISSUE TITLE
Broke with keyframes fallbacks

### ISSUE THREAD

**Issue by aldebaran798** [ChristianMurphy/postcss-combine-duplicated-selectors#81]
When keyframes fallbacks are used  break the CSS

Input    

    @-webkit-keyframes spin {
      0% {
        transform: rotate(0deg);
      }
      100% {
        transform: rotate(360deg);
      }
    }

    @keyframes spin {
      0% {
        transform: rotate(0deg);
      }
      100% {
        transform: rotate(360deg);
      }
    }

Output

    @-webkit-keyframes spin {
      0% {
        transform: rotate(0deg);
      }
      100% {
        transform: rotate(360deg);
      }
    }    

    @keyframes spin {
    }

**Comment by ChristianMurphy** [comment]
Thanks for reporting this @aldebaran798! :+1: 
That definitely is a bug :bug: 
I'll look into this when I have a chance.
As always PRs are welcome :smile:

**Comment by aldebaran798** [comment]
Thanks for support

**Comment by studentIvan** [comment]
10.0.2 still getting this problem

**Comment by ChristianMurphy** [comment]
@studentIvan this has been resolved, there is a test case in the test suite showing it working
https://github.com/ChristianMurphy/postcss-combine-duplicated-selectors/blob/b52a3c9f7599f0288cd5ddaa417245cac5efbad0/test/unique-css.js#L153-L165
and were passing on 10.0.2 https://github.com/ChristianMurphy/postcss-combine-duplicated-selectors/actions/runs/277075595

If you're encountering a keyframes related problem, please open a new issue, and include details of the issue you are seeing.
